version: "3.8"
services:

  react_app:                         
    build:
      context: ./frontend
    container_name: react_app_c
    ports:
      - '3000:3000'
    volumes:                      
      - ./frontend:/react_app
      - /react_app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  
    stdin_open: true         
    # tty: true   
   

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: sumangal
    volumes:
      - ./mysql_data:/var/lib/mysql

  # db:
  #   container_name: postgresql_db
  #   image: postgres
  #   # automatically restarts the container
  #   restart: always
  #   # restart: unless-stopped
  #   volumes:
  #     - ./postgres_data/db:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: sumangal
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     app_net:
  #       ipv4_address: 192.168.0.2   # Giving static ipv4 address to postgreSQL database
  
  app:
    build: ./backend
    command:
      - /bin/bash
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    ports:
      - "8000:8000"
    environment:
    - DEBUG=1
    - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    volumes:
      - ./backend:/app
    depends_on:
      - db
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8077:80'
    environment:
      # - PMA_ARBITRARY=1
      - PMA_HOST=db
    restart: always
    depends_on:
      - db

  # pgadmin:
  #   container_name: pgadmin4
  #   image: dpage/pgadmin4
  #   restart: always
  #   volumes:
  #     - ./pgadmin_data:/var/lib/pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: root@root.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #     # PGADMIN_LISTEN_PORT = 80
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db
  #   networks:
  #     app_net:
  #       ipv4_address: 192.168.0.3   # Giving static ipv4 address to pgAdmim web user interface

volumes:
  mysql_data:
  # postgres_data:
  # pgadmin_data:

# networks:
#   app_net:
#     ipam:
#       driver: default
#       config:
#         - subnet: "192.168.0.0/24"
#           gateway: 192.168.0.1
